### ISSUE TITLE
An example for implementing the package

### ISSUE THREAD

**Issue by chipv-crystal** [zheeeng/pagination#1]
Thanks for sharing useful tips
Can you give an example for implementing this package? Thanks

**Comment by zheeeng** [comment]
Sorry for the delay. I refactored some implementations add three examples with simple testing. It satisfys my demands.

There is a [basic usage](https://godoc.org/github.com/zheeeng/pagination#example-package) for reference, and you can find other examples here.

**Comment by chipv-crystal** [comment]
Thanks @zheeeng . It's working fine now. thanks so much. Thanks for sharing useful tip :)

**Comment by zheeeng** [comment]
@chipv-crystal Hello, just then I released a fresh version, focus on simplifying usage. You can take a look at [README.md](https://github.com/zheeeng/pagination) or [Go Doc](https://godoc.org/github.com/zheeeng/pagination#example-package).

Wish you enjoy it and I look forward to having your feedbacks.
